config/routes.rb
Rails.application.routes.draw do
  resources :lakes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  delegated_type :articleable, types: ['Lake']
end

app/models/concerns/articleable.rb
module Articleable
  extend ActiveSupport::Concern

  included do
    has_one :article, as: :articleable, touch: true, dependent: :destroy
    accepts_nested_attributes_for :article
  end
end

app/models/lake.rb
class Lake < ApplicationRecord
  include Articleable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lakes_controller.rb
class LakesController < ApplicationController
  before_action :set_lake, only: %i[ show edit update destroy ]

  # GET /lakes or /lakes.json
  def index
    @lakes = Lake.all
  end

  # GET /lakes/1 or /lakes/1.json
  def show
  end

  # GET /lakes/new
  def new
    @lake = Lake.new
    @lake.article = Article.new
  end

  # GET /lakes/1/edit
  def edit
    @lake.article = Article.new if @lake.article.nil?
  end

  # POST /lakes or /lakes.json
  def create
    @lake = Lake.new(lake_params)

    respond_to do |format|
      if @lake.save
        format.html { redirect_to lake_url(@lake), notice: "Lake was successfully created." }
        format.json { render :show, status: :created, location: @lake }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lakes/1 or /lakes/1.json
  def update
    respond_to do |format|
      if @lake.update(lake_params)
        format.html { redirect_to lake_url(@lake), notice: "Lake was successfully updated." }
        format.json { render :show, status: :ok, location: @lake }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lakes/1 or /lakes/1.json
  def destroy
    @lake.destroy!

    respond_to do |format|
      format.html { redirect_to lakes_url, notice: "Lake was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lake
      @lake = Lake.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lake_params
      params.require(:lake).permit(:lake_id, article_attributes: [:title, :description])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lakes_helper.rb
module LakesHelper
end

app/views/lakes/_form.html.erb
<%= form_with(model: lake, class: "contents") do |form| %>
  <% if lake.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lake.errors.count, "error") %> prohibited this lake from being saved:</h2>

      <ul>
        <% lake.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :lake_id %>
    <%= form.text_field :lake_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%# we have an associated article, and we have accepts_nested_attributes_for :article on our model %>
  <%= form.fields_for :article do |article_form| %>
    <div class="my-5">
      <%= article_form.label :title %>
      <%= article_form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= article_form.label :description %>
      <%= article_form.text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lakes/_lake.html.erb
<div id="<%= dom_id lake %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Lake:</strong>
    <%= lake.lake_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this lake", lake, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this lake", edit_lake_path(lake), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/lakes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lake</h1>

  <%= render "form", lake: @lake %>

  <%= link_to "Show this lake", @lake, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to lakes", lakes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lakes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lakes</h1>
    <%= link_to "New lake", new_lake_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="lakes" class="min-w-full">
    <%= render @lakes %>
  </div>
</div>

app/views/lakes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lake</h1>

  <%= render "form", lake: @lake %>

  <%= link_to "Back to lakes", lakes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lakes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @lake %>

    <%= link_to "Edit this lake", edit_lake_path(@lake), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this lake", lake_path(@lake), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to lakes", lakes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DelgatedTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>